name: Deploy to GitHub Pages via angular-cli-ghpages

on: 
  push:
    branches:
    - master
  schedule:
  - cron: 0 2 * * 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Prepare
      run: npm install
    
    - name: Run tests
      run: npm test

    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run ng -- deploy --base-href=/cistern-pwa/ --name="SwonVIP" --email="dev@scheffel.ch" --no-silent
