name: Deploy to GitHub Pages via angular-cli-ghpages

on: 
  push:
    branches:
    - master
  schedule:
  - cron: 0 2 * * 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Prepare
      run: npm install
    
    - name: Run unit tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

    #TODO Currently fails due to chrome web driver
    #- name: Run e2e tests
    #  run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run ng -- deploy --base-href=/cistern-pwa/ --name="SwonVIP" --email="dev@scheffel.ch" --no-silent
