name: Deploy to GitHub Pages via angular-cli-ghpages

on: 
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Prepare and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        ls
        npm run ng -- deploy --base-href=/cistern-pwa/ --name="SwonVIP" --email="mail@scheffel.ch" --no-silent
