name: Deploy to GitHub Pages via angular-cli-ghpages

on: 
  push:
    branches:
    - master
  schedule:
  - cron: 0 2 * * 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Prepare
      run: npm install

    - name: Install latest Google Chrome
      run: sudo apt-get update && sudo apt-get remove google-chrome-stable -y && sudo apt-get install google-chrome-stable -y

      #If newer Chrome is installed update used chromewebdriver in NPM script. Currently 80.0.0
    - name: Check installed Google Chrome version
      run: google-chrome --version

    - name: Run unit tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

    - name: Run e2e tests
      run: npm run e2e --protractor-config=e2e/protractor-ci.conf.js

    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run ng -- deploy --base-href=/cistern-pwa/ --name="SwonVIP" --email="dev@scheffel.ch" --no-silent
